# Generated by Django 4.2 on 2023-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
